# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MemoWithTags' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MemoWithTags
  pod 'onnxruntime-objc', '~> 1.20.0'
end
